name: CI for egg

on: # when this action should be triggered?
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: # jobs are made of steps
  build:
    # Define the OS our workflow should run on
    runs-on: ${{ matrix.os }}

    strategy:
      # To test across multiple language versions
      matrix:
        node-version: [15.x, 16.x, 17.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps: # Clone the repo. See https://github.com/actions/checkout
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    # Example of using an environment variable
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1 # Install node. See https://github.com/actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
    - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
    - run: npm install
    - run: npm install @ull-esit-pl-2122/lexer-generator-daniel-hernandez-de_leon-alu0101331720
    - run: npm test
      # Environment variables
      env:
        CI: true
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
